version: 0.0.{build}
image: Visual Studio 2017
before_build:
  - cmd: cd src
  

build_script:
  - cmd: dotnet restore
  - cmd: dotnet build --configuration Release
  - cmd: dotnet pack AutoUpdate.Core\AutoUpdate.Core.csproj --configuration Release --include-symbols --no-build -p:PackageVersion=%APPVEYOR_BUILD_VERSION% --version-suffix %APPVEYOR_REPO_COMMIT%

test_script:
- cmd:  dotnet test test\AutoUpdate.Core.Tests\AutoUpdate.Core.Tests.csproj --configuration Release --no-build --test-adapter-path:. --logger:Appveyor

artifacts:
    - path: '**\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: MbmfXcBlXOa/UjZj6W1UR4/OkHuqZ+TnqqUcMmA0tV0ifSkSVX41+L1XeCF46eNH
  artifact: /.*\.nupkg/
  skip_symbols: true
  on:
    branch: master