version: 0.0.{build}
image: Visual Studio 2017
before_build:
  - cmd: cd src
  

build_script:
  - cmd: dotnet restore
  - cmd: dotnet build  
  - cmd: dotnet pack AutoUpdate.Core\AutoUpdate.Core.csproj --configuration Release --no-build -p:PackageVersion=%APPVEYOR_BUILD_VERSION%

test_script:
- cmd:  dotnet test test\AutoUpdate.Core.Tests\AutoUpdate.Core.Tests.csproj --configuration Debug --no-build --test-adapter-path:. --logger:Appveyor

deploy:
- provider: NuGet
  api_key:
    secure: +yeoLimNe2kLA4Bw/Yl/1/u2V4gddgzl7z8QnFQd8SDWRIqsUBBgm7fafPbt98qg
  skip_symbols: true
  on:
    branch: master