version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: >-
    cd src

    dotnet restore

build:
  parallel: true
  verbosity: normal

test_script:
- cmd: >-
    dir 

    dotnet test ~\test\AutoUpdate.Core.Tests\AutoUpdate.Core.Tests.csproj --configuration Debug --no-build --test-adapter-path:. --logger:Appveyor